---
- name: Restart Backend Application Process via API
  hosts: localhost
  tasks:
    - name: Restart the application process via API
      uri:
        url: "http://20.235.19.18:2107/restart_processremedial"
        method: POST
        return_content: yes
      register: api_response
      
    - name: Print API response
      debug:
        msg: "API response: {{ api_response.content }}"
        
    - name: Fail the play if the API call was not successful
      fail:
        msg: "Failed to restart the application process via API."
      when: api_response.status != 200
